name: buildRelease
on:
  workflow_dispatch:

env:
  AWS_REGION: 'us-east-1'

jobs:
  pfml-cal-benefits-deploy-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-node@v3
      with:
        node-version: "10.10.0"
    - name: Install global packages
      run: npm install -g axios@0.19.0 && npm install
    - name: PFML Benefits Calculator Install Packages
      run: cd PFML/BenefitsCalculator && npm install
    - name: PFML Benefits Calculator Deploy Dev App
      run: |-
        cd PFML/BenefitsCalculator && npm run build:development
    
    - name: compress  
      run: |
        cd PFML/BenefitsCalculator/build
        tar -cvzf build.tar.gz *
        zip -r pfml_benefit.zip *
      continue-on-error: true
    - name: create artifact folder
      run: |
        mkdir -p /tmp/artifacts
        cp PFML/BenefitsCalculator/build/pfml_benefit.zip /tmp/artifacts
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pfml_benefit
        path: /tmp/artifacts
  pfml-cal-contribution-deploy-dev:
    runs-on: ubuntu-latest
    needs: pfml-cal-benefits-deploy-dev
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}
    - uses: actions/setup-node@v3
      with:
        node-version: "10.10.0"
    - name: Install global packages
      run: npm install
    - name: PFML Contribution Calculator Install Packages
      run: cd PFML/ContributionCalculator && npm install
    - name: PFML Contribution Calculator Deploy Dev App
      run: |-
        cd PFML/ContributionCalculator && npm run build:development
    
    - name: compress  
      run: |
        cd PFML/ContributionCalculator/build
        tar -cvzf build.tar.gz *
        zip -r pfml_contribution.zip *
      continue-on-error: true
    - name: create artifact folder
      run: |
        mkdir -p /tmp/artifacts
        cp PFML/ContributionCalculator/build/pfml_contribution.zip /tmp/artifacts
    - name: upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: pfml_contribution
        path: /tmp/artifacts
  release:
    runs-on: ubuntu-latest
    needs: pfml-cal-contribution-deploy-dev
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.ref }}    
    - name: download pfml-benefit artifact
      uses: actions/download-artifact@v3
      with:
        path: /tmp/artifacts
#        name: pfml_benefit.zip
    - name: move zip file to root directory
      run: |
        pwd
        tree /tmp/artifacts           
        for f in $(find tmp/artifacts -name '*.zip'); do cp $f .; done
        tree .
      continue-on-error: false     
    - name: 'Get semver based on pr label'
      id: semver
      uses: "snsinahub-org/semver@v2.2.0"
      with:
        type: 'MINOR'
        prefix: 'v'
        body: 'PFML BenefitsCalulator: Initial release'
        create-release: 'yes'
        files: |
            pfml_benefit.zip
            pfml_contribution.zip
      continue-on-error: false
    - name: 'print version'        
      run: |
        echo ${{ steps.semver.outputs.version }}
